In [2]:
import numpy as np

In [3]:
n1=np.array([1,2,3])
n1

array([1, 2, 3])

In [4]:
print(n1.shape)
print(n1.size)
print(n1.ndim)
print(n1.dtype)

(3,)
3
1
int64


In [5]:
n2=np.array([[1,2,3,4,5],[3,4,5,6,7]])
n2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [6]:
print(n2.shape)
print(n2.size)
print(n2.ndim)
print(n2.dtype)


(2, 5)
10
2
int64


*create 2 1D array each of 5 elements and apply vector operations like addition and subtraction*

In [7]:
num1=[1,2,3,4,5]
num2=[6,7,8,9,10]
print(np.add(num1,num2))
print(np.subtract(num1,num2))

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]


array of zeros

In [8]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

array of ones

In [9]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

create of 3d array of shape 4x3x2 of all zero elements

In [10]:
np.zeros((4,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

create an identity matrix using eye method 

In [11]:
np.eye(3,dtype=str)

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

In [12]:
n1=np.array([1,2,3])
n2=np.array([2,1,4])
n1>n2

array([False,  True, False])

apply logical not operation on an input array

In [14]:
c1=np.eye(3)
c2=np.logical_not(c1).astype(int)
c2

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

create an array of 3 elements 5,7,9. create deep and shallow copy of this array

In [19]:
arr=np.array([5,7,9])
arr1=arr.copy
arr2=arr.view
print(arr1)
print(arr2)


<built-in method copy of numpy.ndarray object at 0x0000020F393B8C90>
<built-in method view of numpy.ndarray object at 0x0000020F393B8C90>


In [20]:
arr=np.array([2,3,4])
arr+5

array([7, 8, 9])

create 2d array of 4x2 and reshape into 2d array of 4x2 (RESHAPE)

In [31]:
arr=np.array([[2,3],[5,6],[7,8],[9,10]])
print(arr.reshape(2,4))
print(arr.ravel())

[[ 2  3  5  6]
 [ 7  8  9 10]]
[ 2  3  5  6  7  8  9 10]


INDEXING AND SLICING

consider a 2D array of shape 2x4 and 