In [82]:
import numpy as np

CREATING ARRAY

In [83]:
a=np.array([1,2,3])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


SPECIAL ARRAYS

In [84]:
a=np.zeros((3,4))  # array of zeros
print(a)
b=np.ones((2,3))  #array of ones
print(b)
c=np.eye(3)   #identity matrix
print(c)
d=np.arange(0,20,3)  #(from,to,step)
print(d)
e=np.linspace(0,5,3) #(from,to,number of random values)
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  3  6  9 12 15 18]
[0.  2.5 5. ]


ARRAY ATTRIBUTES

In [85]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape) #(rows,cols)
print(a.ndim) #(total number of dimensions)
print(a.size) #no of elements
print(a.dtype) #data type of elements

(2, 3)
2
6
int64


ARRAY INDEXING AND SLICING

In [86]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])  # element at 1st row, 2nd column => 2
print(arr[:, 1])     # all rows, 2nd column => [2, 5]
print(arr[1, :])     # 2nd row => [4, 5, 6]


2
[2 5]
[4 5 6]


ARRAY OPERTIONS

In [87]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)         # [5, 7, 9]
print(a * b)         # [4, 10, 18]
print(a ** 2 )       # [1, 4, 9]



[5 7 9]
[ 4 10 18]
[1 4 9]


BROADCASTING

In [88]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


MULTIPLICATION

In [89]:
a=np.array([[1,2],[4,5]])
b=np.array([[6,7],[2,3]])
print(np.dot(a,b))

[[10 13]
 [34 43]]


TRANSPOSE

In [90]:
print(a.T)

[[1 4]
 [2 5]]


INVERSE

In [91]:
a=np.array([[1,2],[4,5]])
b=np.array([[6,7],[2,3]])
print(np.linalg.inv(a))
print(np.linalg.inv(b))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[ 0.75 -1.75]
 [-0.5   1.5 ]]


DETERMINANT

In [92]:
arr=np.array([[56,43],[39,41]])
print(np.linalg.det(arr))

619.0000000000006


AGGREGATION FUNCTIONS

In [93]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(np.sum(arr)) #total sum
print(np.mean(arr)) #mean
print(np.max(arr, axis=0)) #max of each col
print(np.min(arr, axis=1)) # min of each row
print(np.std(arr)) # standard deviation

42
4.666666666666667
[6 7 8]
[1 4 6]
2.2110831935702664


MASKING AND FILTERING

In [94]:
arr=np.array([2,3,4,6,7,8])
mask=arr>3
print(arr[mask])

[4 6 7 8]


RESHAPING & STACKING

In [95]:
s="Random Module"
print(s.upper())

RANDOM MODULE


In [96]:
arr = np.arange(6).reshape(2, 3)   # reshape to 2 rows, 3 cols
print(arr)
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack([a, b])  )  # vertical stack
print(np.hstack([a, b]))    # horizontal stack


[[0 1 2]
 [3 4 5]]
[[1 2]
 [3 4]]
[1 2 3 4]


*RANDOM MODULE

In [97]:
np.random.seed(69) # produces the same result (pics same 3 random numbers everytime)
print(np.random.rand(4)) 
print(np.random.rand(3,3)) # pics random number in matrix of size 2x3 from range [0,1)
print(np.random.randn(2,3)) #centered around 0(can be negative)
print(np.random.randint(0,10,(2,3))) # random nums from 0 to 10 of size 2x3

[0.29624916 0.80906772 0.35025253 0.78940926]
[[0.56134898 0.25358895 0.10497708]
 [0.05846073 0.67329238 0.69782966]
 [0.73278321 0.78787406 0.07637632]]
[[ 1.13178979 -0.85612992 -0.35230503]
 [-2.02389307 -0.54447703 -0.98382907]]
[[6 5 1]
 [6 5 7]]


USEFUL UTILITIES

In [100]:
arr=np.array([3,4,1,2,6])
print(np.unique([1,2,3,4,5,5])) # behaves like set
print(np.where(arr>3,1,0)) #np.where(condition , replace by x if true, replace by y if false)
print(np.clip(arr,2,4)) # np.clip(arr,min,max) values below min will be replaced by min and values above max will be replaced by max 

[1 2 3 4 5]
[0 1 0 0 1]
[3 4 2 2 4]


STANDARDIZE TO MAKE MEAN=0 DEVIATION=1

In [102]:
data = np.array([12, 15, 20, 21, 18])
mean = np.mean(data)
std = np.std(data)

standardized = (data - mean) / std
print(standardized)
print(np.mean(standardized))
print(np.std(standardized))



[-1.57071744 -0.6645343   0.84577093  1.14783198  0.24164884]
2.886579864025407e-16
1.0
